SELECT A.CPF, T.NOME
FROM ATLETA A
    JOIN TIME T ON A.ATL_SIGLA_TIME = T.SIGLA_TIME;

SELECT *
FROM ATLETA A
    JOIN TIME T ON A.ATL_SIGLA_TIME = T.SIGLA_TIME
ORDER BY A.NOME;

SELECT COUNT ( * )
FROM ATLETA A
    LEFT JOIN TIME T ON A.ATL_SIGLA_TIME = T.SIGLA_TIME
ORDER BY A.NOME;

SELECT *
FROM ESTAT_PARTIDA;

SELECT E.EST_LOCAL, MIN (E.VALOR) , SUM (E.VALOR) -- E.CRITERIO,E.VALOR --,MIN(ATL_SIGLA_ESPORTE) , count(*)
FROM ESTAT_PARTIDA E
GROUP BY E.EST_LOCAL
HAVING SUM (E.VALOR) > 10;

SELECT *
FROM ATLETA
ORDER BY DATA;

SELECT *
FROM ATLETA A
WHERE A.DATA > (
        SELECT MIN (DATA)
        FROM ATLETA
    )
ORDER BY A.DATA;

SELECT *
FROM TREINADOR;

SELECT *
FROM TIME;

SELECT *
FROM PARTIDA;

SELECT *
FROM DISPUTA;

SELECT T.SIGLA_ESPORTE, T.NOME, A.NOME, A.CPF, TO_CHAR (P."DATA", 'DD/MM/YYYY HH24:MI:SS') AS DATA, P."LOCAL"
FROM DISPUTA D
    JOIN TIME T ON T.SIGLA_TIME = D.SIGLA_TIME
    AND T.SIGLA_ESPORTE = D.SIGLA_ESPORTE
    JOIN PARTIDA P ON D.EST_DATA = P.DATA
    AND D.EST_LOCAL = P.LOCAL
    JOIN ATLETA A ON A.ATL_SIGLA_TIME = T.SIGLA_TIME
ORDER BY T.NOME, A.NOME;

SELECT *
FROM MEDICO;

SELECT *
FROM EXAME;

SELECT *
FROM ORTOPEDICO;

SELECT *
FROM NEUROLOGICO;

SELECT *
FROM EXAME e
ORDER BY E.TIPO;

SELECT *
FROM EXAME E
    JOIN MAPEAMENTO_GENETICO M ON M.EXAME = E.PROTOCOLO;

SELECT *
FROM MAPEAMENTO_GENETICO M;

select * from IMAGEM_OSSEA ;